version: '{build}'
branches:
  only:
  - master
clone_folder: c:\projects\klex
image:
- Visual Studio 2017
configuration:
- Release
- Debug
platform:
- x64
- x86

matrix:
  fast_finish: true

# skip unsupported combinations
init:
- set arch=
- if "%PLATFORM%"=="x64" (set arch= Win64)
- echo %arch%
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator="Visual Studio 14 2015%arch%" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" ( set generator="Visual Studio 12 2013%arch%" )
- echo %generator%

build_script:
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - echo %generator%
  - echo %CONFIGURATION%
  - cmake -G %generator% --config %CONFIGURATION% ..
  - cmake --build . --config %CONFIGURATION%

test_script:
  - .\klex_test.exe

only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - src/
    - examples/
    - docs/
    - cmake/
    - 3rdparty/
