version: '{build}'
branches:
  only:
  - master
clone_folder: c:\projects\klex
image:
- Visual Studio 2017
configuration:
- Release
- Debug
platform:
- x64
- x86

matrix:
  fast_finish: true

build_script:
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - cmake -G "%GENERATOR%" --config "%CONFIGURATION%" ..
  - cmake --build . --config "%CONFIGURATION%"

test_script:
  - .\build\klex_test

only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - src/
    - examples/
    - docs/
    - cmake/
    - 3rdparty/
