version: '{build}'
branches:
  only:
  - master
clone_folder: c:\projects\klex
image:
- Visual Studio 2017
configuration:
- Release
- Debug
platform:
- x64

matrix:
  fast_finish: true

environment:
  matrix:
    - GENERATOR: "Visual Studio 15 Win64"
      CONFIG: Debug

    - GENERATOR: "Visual Studio 15 Win64"
      CONFIG: Release

build_script:
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - cmake -G "%GENERATOR%" --config "%CONFIG%" ..
  - cmake --build . --config "%CONFIG%"

test_script:
  - .\build\klex_test

only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - src/
    - examples/
    - docs/
    - cmake/
    - 3rdparty/
