# vim:ts=2:sw=2:et
version: 2

# -----------------------------------------------------------------------------------------------
defaults:

  - workflow_trigger_on_tags: &workflow_trigger_on_tags
      filters:
        tags:
          only: /.*/

  - run_prepare: &run_prepare
      name: Prepare
      command: |
        set -ex
        apt-get -q update
        apt-get -qy install cmake clang++-8

  - run_build: &run_build
      name: Build
      command: |
        set -ex
        mkdir -p build
        cd build
        cmake .. -G "Unix Makefiles" \
            -DCMAKE_CXX_COMPILER=$CMAKE_CXX_COMPILER \
            -DCMAKE_C_COMPILER=$CMAKE_C_COMPILER \
            -DCMAKE_BUILD_TYPE="$CMAKE_BUILD_TYPE" \
            $CMAKE_OPTIONS
        make -j3

  - run_test: &run_test
      name: klex_test
      command: ./build/klex_test

  - run_git_sm_init: &run_git_sm_init
      name: git submodule init
      command: git submodule update --init

# -----------------------------------------------------------------------------------------------
jobs:

  build_ubuntu1904_gcc:
    docker:
      - image: buildpack-deps:disco
    environment:
      CMAKE_BUILD_TYPE: "Release"
      CMAKE_C_COMPILER: "gcc-8"
      CMAKE_CXX_COMPILER: "g++-8"
    steps:
      - checkout
      - run: *run_git_sm_init
      - run: *run_prepare
      - run: *run_build
      - run: *run_test
      - persist_to_workspace:
          root: build
          paths:
            - "*"

  build_ubuntu1904_clang:
    docker:
      - image: buildpack-deps:disco
    environment:
      CMAKE_BUILD_TYPE: "Release"
      CMAKE_C_COMPILER: "clang-8"
      CMAKE_CXX_COMPILER: "clang++-8"
    steps:
      - checkout
      - run: *run_git_sm_init
      - run: *run_prepare
      - run: *run_build
      - run: *run_test
      - persist_to_workspace:
          root: build
          paths:
            - "*"

workflows:
  version: 2

  build_and_test:
    jobs:
      - build_ubuntu1904_gcc: *workflow_trigger_on_tags
      - build_ubuntu1904_clang: *workflow_trigger_on_tags
